### ISSUE TITLE
MacOS M1 wheel is broken

### ISSUE THREAD

**Issue by niclaurenti** [niclaurenti/adani#31]
When installing the wheel with `pip install adani` it fails with the following error:
```
>>> import adani
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/adani/__init__.py", line 1, in <module>
    from ._core import *
ImportError: dlopen(/opt/homebrew/lib/python3.11/site-packages/adani/_core.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_gsl_rng_default'
>>> 
```

**Comment by niclaurenti** [comment]
solved in #32
